FROM mcr.microsoft.com/dotnet/core/sdk:3.1-alpine AS build

WORKDIR /Commander

# copy csproj and restore as distinct layer
COPY ./commander.csproj ./commander.csproj
# install dependencies
RUN dotnet restore ./commander.csproj

# copy everything else and build
COPY . .
# build for production
RUN dotnet publish ./commander.csproj \
  --runtime linux-musl-x64 \
  -c RELEASE \
  -o out /p:Version=1.0.0
  #\ -p:PublishTrimmed=true

FROM alpine:3.1

WORKDIR /app

COPY --from=build ./Commander/out .

EXPOSE 5000

ENTRYPOINT [ "./commander" ]